/*
 * generate.mjs — emit generated sources from the CTP headers.
 *
 * Outputs (src/generated/):
 *   enums.gen.ts   — TS enums (PascalCase) for every CTP char-enum family
 *   structs.gen.ts — TS interfaces (camelCase fields) + runtime field descriptors
 *   layout.gen.h   — declaration of the C++ layout-data accessor
 *   layout.gen.cc  — offsetof/sizeof tables (compiler-truth field layout)
 *
 * Field kinds: 0 = string (char / char[] / enum), 1 = int32, 2 = int16, 3 = double
 */

import { writeFile, mkdir } from "node:fs/promises";
import { parseDataTypes, parseStructs } from "./parse.mjs";
import { camelCase, structTypeName } from "./naming.mjs";

const ROOT = new URL("../../", import.meta.url);
const DT = new URL("tradeapi/ThostFtdcUserApiDataType.h", ROOT);
const ST = new URL("tradeapi/ThostFtdcUserApiStruct.h", ROOT);
const OUT = new URL("src/generated/", ROOT);

const { types, enums } = await parseDataTypes(DT);
const structsRaw = await parseStructs(ST);

const kindOf = (t) =>
  t.kind === "int32" ? 1 : t.kind === "int16" ? 2 : t.kind === "double" ? 3 : 0;
const tsTypeOf = (t) =>
  t.kind === "enum" ? "enums." + t.enumName :
  t.kind === "string" || t.kind === "char" ? "string" : "number";
const jsdoc = (c) => (c ? c.replace(/\*\//g, "* /") : "");

// Resolve structs: assign ids, camelCase fields, drop fields with unknown types
// (their absence does not affect other fields' offsets, which are absolute).
const usedNames = new Map();
const structs = structsRaw.map((s) => {
  let name = structTypeName(s.cName);
  if (usedNames.has(name)) name = `${name}_${usedNames.get(name) + 1}`;
  usedNames.set(structTypeName(s.cName), (usedNames.get(structTypeName(s.cName)) || 0) + 1);
  const fields = s.fields
    .map((f) => ({ ...f, js: camelCase(f.cName), t: types.get(f.ctpType) }))
    .filter((f) => f.t);
  return { cName: s.cName, name, fields };
});

// Disambiguate enum names against struct interface names (and each other): a
// clean enum name colliding with a struct gets a "Type" suffix. Field type
// references read t.enumName, so update it too.
const structNameSet = new Set(structs.map((st) => st.name));
const usedEnumNames = new Set();
for (const en of enums) {
  let cand = en.name;
  let i = 1;
  while (structNameSet.has(cand) || usedEnumNames.has(cand)) {
    cand = `${en.name}Type${i > 1 ? i : ""}`;
    i++;
  }
  usedEnumNames.add(cand);
  en.finalName = cand;
  const t = types.get(en.ctpType);
  if (t) t.enumName = cand;
}

// ---------- enums.gen.ts ----------
let e = `/* AUTO-GENERATED by scripts/codegen/generate.mjs. Do not edit. */\n\n`;
for (const en of enums) {
  e += `/** ${en.ctpType} */\nexport enum ${en.finalName} {\n`;
  const seen = new Set();
  for (const m of en.members) {
    let mn = /^[0-9]/.test(m.name) ? "_" + m.name : m.name;
    if (seen.has(mn)) continue;
    seen.add(mn);
    e += `  ${mn} = ${JSON.stringify(m.value)},\n`;
  }
  e += `}\n\n`;
}

// ---------- structs.gen.ts ----------
let s = `/* AUTO-GENERATED by scripts/codegen/generate.mjs. Do not edit. */\n\n`;
s += `import * as enums from "./enums.gen.js";\n\n`;
for (const st of structs) {
  s += `/** ${st.cName} */\nexport interface ${st.name} {\n`;
  for (const f of st.fields) {
    if (f.comment) s += `  /** ${jsdoc(f.comment)} */\n`;
    s += `  ${f.js}: ${tsTypeOf(f.t)};\n`;
  }
  s += `}\n\n`;
}
s += `/** Field descriptor: js name + kind (0 string, 1 i32, 2 i16, 3 f64). */\n`;
s += `export interface FieldDesc { js: string; kind: number; }\n`;
s += `export interface StructDesc { id: number; name: string; cName: string; fields: FieldDesc[]; }\n\n`;
s += `/** Runtime descriptors; order matches layout.gen.cc (id = index). */\n`;
s += `export const STRUCTS: StructDesc[] = [\n`;
structs.forEach((st, id) => {
  const fs = st.fields
    .map((f) => `{ js: ${JSON.stringify(f.js)}, kind: ${kindOf(f.t)} }`)
    .join(", ");
  s += `  { id: ${id}, name: ${JSON.stringify(st.name)}, cName: ${JSON.stringify(st.cName)}, fields: [${fs}] },\n`;
});
s += `];\n\n`;
s += `export const STRUCT_ID: Readonly<Record<string, number>> = {\n`;
structs.forEach((st, id) => (s += `  ${JSON.stringify(st.name)}: ${id},\n`));
s += `};\n`;

// ---------- layout.gen.h / layout.gen.cc ----------
const h = `/* AUTO-GENERATED. Do not edit. */
#ifndef CTP_LAYOUT_GEN_H
#define CTP_LAYOUT_GEN_H
#include <cstddef>
#include <cstdint>
const int32_t *ctpLayoutData(size_t *outLen);
int32_t ctpMaxStructSize();
#endif
`;

let c = `/* AUTO-GENERATED. Do not edit. */
#include "layout.gen.h"
#include "ThostFtdcUserApiStruct.h"
#include <cstddef>

const int32_t *ctpLayoutData(size_t *outLen) {
  static const int32_t data[] = {
    ${structs.length},
`;
structs.forEach((st, id) => {
  c += `    /* [${id}] ${st.name} */\n`;
  c += `    (int32_t)sizeof(${st.cName}), ${st.fields.length},\n`;
  for (const f of st.fields) {
    c += `    (int32_t)offsetof(${st.cName}, ${f.cName}), (int32_t)sizeof(${st.cName}::${f.cName}), ${kindOf(f.t)},\n`;
  }
});
c += `  };
  *outLen = sizeof(data) / sizeof(data[0]);
  return data;
}

int32_t ctpMaxStructSize() {
  size_t len = 0;
  const int32_t *d = ctpLayoutData(&len);
  int32_t maxSz = 0;
  size_t p = 1;
  const int32_t n = d[0];
  for (int32_t i = 0; i < n; ++i) {
    if (d[p] > maxSz) maxSz = d[p];
    p += 2 + static_cast<size_t>(d[p + 1]) * 3;
  }
  return maxSz;
}
`;

// ---------- structids.gen.h ----------
let sid = `/* AUTO-GENERATED. Do not edit. */\n#ifndef CTP_STRUCTIDS_GEN_H\n#define CTP_STRUCTIDS_GEN_H\n`;
structs.forEach((st, id) => (sid += `#define SID_${st.name} ${id}\n`));
sid += `#endif\n`;

await mkdir(OUT, { recursive: true });
await writeFile(new URL("enums.gen.ts", OUT), e);
await writeFile(new URL("structs.gen.ts", OUT), s);
await writeFile(new URL("layout.gen.h", OUT), h);
await writeFile(new URL("layout.gen.cc", OUT), c);
await writeFile(new URL("structids.gen.h", OUT), sid);

console.log(`generated ${enums.length} enums, ${structs.length} structs -> src/generated/`);
